CFIN-159 Call Funnelback API
university-of-york/uoy-api-courses pull request #17
Opened 2020-09-07 13:40 UTC by ChristianBeddows

This is what I'd consider the smallest amount of work to get the Lambda to retrieve data from Funnelback. 
Interested in people's thoughts on what functionality this endpoint should have at this point (e.g. I haven't added 'max' or 'offset' parameters for pagination), and at what point we should split some of this functionality into separate functions (like we do for requests in the proposals app).

2020-09-07 14:28 UTC, FergusMcGlynn requested changes
There are no tests yet. I think even the minimal solution would involve a test that verifies that the Funnelback API is being called with the expected parameters

2020-09-07 14:28 UTC, FergusMcGlynn commented on api/handler.js
> +  let response = await fetch(url, {
I think these could all be `const` rather than `let`. I get the impression from JS aficionados that it's considered cleaner to use `const` where possible, and only use `let` if it's really necessary (i.e. there's no reasonable immutable solution)

2020-09-08 09:55 UTC, ncn1 commented on api/handler.js
> +  let response = await fetch(url, {
Agree

2020-09-08 16:10 UTC, ce666-york approved these changes
I've run the tests locally and deployed to my sandbox and it all works great 🙂

2020-09-09 08:59 UTC, FergusMcGlynn approved these changes

2020-09-09 14:44 UTC, closed without merging