CFIN-234 add tags
university-of-york/uoy-api-courses pull request #19
Opened 2020-09-08 15:15 UTC by ncn1

2020-09-08 15:45 UTC, ce666-york approved these changes

2020-09-08 16:10 UTC, FergusMcGlynn requested changes

2020-09-08 16:10 UTC, FergusMcGlynn commented on .github/workflows/deploy.yml
> +          DEPLOY_ENVIRONMENT: production
This value needs to be `prod`, not `production`, according to [the wiki page on AWS tags](https://wiki.york.ac.uk/display/AWS/0001+-+Resource+Tagging+Policy). I'm sorry that I didn't spot this earlier when we were making these edits.

2020-09-08 16:10 UTC, FergusMcGlynn commented on api/serverless.yml
> +    repo_name: uoy-api-courses,
I don't think there should commas at the end of any of these lines. Apologies again for not spotting this when we were editing this file!

2020-09-10 09:32 UTC, ChristianBeddows commented on api/serverless.yml
> +    repo_name: uoy-api-courses,
+1. Easy mistake to make when we've been working with JSON a lot

2020-09-10 09:32 UTC, ChristianBeddows approved these changes

2020-09-10 14:42 UTC, FergusMcGlynn approved these changes

2020-09-11 10:16 UTC, merged