CFIN-215 Refactored Error Handling
university-of-york/uoy-api-courses pull request #24
Opened 2020-09-11 14:23 UTC by ChristianBeddows

I've done some refactoring and I feel the code is much more readable this way.

2020-09-11 15:21 UTC, ncn1 approved these changes

2020-09-15 13:30 UTC, ce666-york requested changes
See comments, I think we should add the tests, the rest I'd like to see changed but I'm ok with approving as-is.

2020-09-16 11:36 UTC, FergusMcGlynn requested changes

2020-09-16 11:36 UTC, FergusMcGlynn commented on api/utils/generateUrl.js
> +module.exports = parameters => {
I find it a bit odd to have this as an anonymous function. That could be due to my inexperience with Javascript. A function's name is the developer's best guide as to what the function does, so not having a name makes it harder to understand. Could we give it a name?

2020-09-16 11:36 UTC, FergusMcGlynn commented on api/utils/generateUrl.js
> +module.exports = parameters => {
Also, I find the filename `generateUrl` a tad woolly - generate what url? It's generating a Funnelback API request, so perhaps it could be renamed to reflect that purpose, e.g. `generateFunnelbackAPIRequest` or `generateYorkwebSearchRequestUrl` or something like that?

2020-09-17 10:41 UTC, ChristianBeddows commented on api/handler.js
> +    if (e instanceof ClientError) {
No, you can only have a single catch block in Javascript, presumably due to the lack of typing/proper classes.

The most relevant examples I found both use `instanceof`:
![Screenshot from 2020-09-17 11-33-51](https://user-images.githubusercontent.com/17494696/93459704-06de1c80-f8da-11ea-93dc-448012c05584.png)
![Screenshot from 2020-09-17 11-35-29](https://user-images.githubusercontent.com/17494696/93459714-0b0a3a00-f8da-11ea-9541-bb4162f1947e.png)

However, I've also heard that `instanceof` is a bit smelly, though I don't know why, so I can re-write this if statement as:
![Screenshot from 2020-09-17 11-40-51](https://user-images.githubusercontent.com/17494696/93460126-adc2b880-f8da-11ea-98b2-0982e810a564.png)

2020-09-17 10:47 UTC, ChristianBeddows commented on api/utils/generateUrl.js
> +        throw new ClientError('The search parameter is required.');
This was my initial thought too - and maybe its something to enhance in the future.

Had a discussion with Chris and we decided that showing this message is appropriate:
If the user does not provide a query string, Funnelback will return nothing - not even an empty list. We don't yet have a way of retrieving a list of all results, so it seems better to tell the consumer to search for something rather than show them nothing (or replace the response with an empty list)

2020-09-17 10:55 UTC, ChristianBeddows commented on api/utils/generateUrl.js
> +module.exports = parameters => {
This is a different syntax for `export default function` - so whilst it doesn't have an explicit name in here, the file is named and this will be shown in other files as `import generateUrl from...` - I thought this was adequate for now .

I'm not overly fond of the current naming either. How would you feel about this file being called `constructFunnelbackUrls` and this function being called `coursesUrl` (I remember a past conversation about this being js convention instead of `getCoursesUrl`?). I feel this might lead to more semantic usage such as:
`import {coursesUrl} from constructFunnelbackUrls`
`const url = coursesUrl(parameters);`

2020-09-17 11:17 UTC, FergusMcGlynn commented on api/utils/generateUrl.js
> +module.exports = parameters => {
That sounds good! :)

2020-09-17 11:21 UTC, ChristianBeddows commented
Didn't mean to close this

2020-09-17 12:33 UTC, RichardAllum commented on api/utils/generateUrl.js
> +        throw new ClientError('The search parameter is required.');
OK, if that's the case what should we be doing in this function? If this method is a simple utility method to construct a URL, it shouldn't be doing validation on the client's request - that should be handled by the orchestrator/handler method. I'll add a suggestion to the more up-to-date code.

2020-09-17 12:39 UTC, RichardAllum requested changes

2020-09-17 12:39 UTC, RichardAllum commented on api/utils/constructFunnelbackUrls.js
> +    }
```suggestion

```
There's another suggestion to go with this in handler.js

I've not changed the tests here, but am happy to pair with you on any changes.

2020-09-17 12:39 UTC, RichardAllum commented on api/handler.js
> +    const url = coursesUrl(event.queryStringParameters);
```suggestion

    if (!event.queryStringParameters || !event.queryStringParameters.search) {
        return error('The search parameter is required.', 400, 'Bad Request', event.path);
    }
    const url = coursesUrl(event.queryStringParameters);
```
By placing the validation of the client's request in the handler we can more easily adjust the validation in future, and maybe drop the complexity from multiple error types in the 'catch' block below. Some interesting discussion on when to throw exceptions vs returning null is [here](https://softwareengineering.stackexchange.com/questions/228287/returning-null-or-a-empty-value-throw-exception).

2020-09-17 14:23 UTC, ChristianBeddows commented on api/handler.js
> +    const url = coursesUrl(event.queryStringParameters);
I can see where you're coming from but I don't know if it'd provide any real benefit at this stage - if we're going to work on request validation in the future I suspect we might need to move all this into a separate file anyway?

2020-09-17 14:43 UTC, RichardAllum commented on api/handler.js
> +    const url = coursesUrl(event.queryStringParameters);
It's to pull the validation and exception throwing out of the URL builder, as right now we've got a function that should be doing pure logic (taking parameters and turning them into a URL) with side effects (validating the user request and throwing an exception). If we do need to move it into a separate file it should also be easier to do from handler since it's more visible.

2020-09-18 10:18 UTC, ce666-york approved these changes

2020-09-18 10:30 UTC, ChristianBeddows commented on api/handler.js
> +    const url = coursesUrl(event.queryStringParameters);
I've created technical debt story CFIN-288 to deal with this issue in the future, following a discussion about meeting the API milestone today.

2020-09-18 10:31 UTC, ChristianBeddows commented
I'm closing this now, and will manually merge and consolidate my changes for a merge into dev.

2020-09-18 10:31 UTC, closed without merging