CFIN 281 Add Prettier and XO
university-of-york/uoy-api-courses pull request #35
Opened 2020-09-24 16:41 UTC by ncn1

2020-09-25 11:31 UTC, FergusMcGlynn approved these changes

2020-09-25 11:31 UTC, FergusMcGlynn commented on .xo-config.json
> +  "space": true
I found that I needed to amend this and specify that 4 spaces is our standard (as automated by prettier) or I got XO errors in various places.
```suggestion
  "space": 4
```

2020-09-25 13:06 UTC, ncn1 commented on .xo-config.json
> +  "space": true
Happy to change it, but have not had any of those errors.

2020-09-25 15:28 UTC, ce666-york requested changes
I'd like to tie up the uncertainty around using React libraries - all of my suggestions create a version that works locally for me, but I want to check whether there's a specific reason we're including them.

2020-09-25 15:51 UTC, FergusMcGlynn commented on package.json
> +    "eslint-plugin-react-hooks": "^4.1.2",
Oh yeah! Good point!

2020-09-28 09:16 UTC, ncn1 commented on .xo-config.json
> +  "extends": ["xo-react", "prettier", "prettier/react"],
I copied and pasted from the Course Search,  without registering the API didn't use react. Got a little bogged down with it all, was hoping reviewers would spot stuff like this!

2020-09-28 15:21 UTC, ncn1 commented
Going to close and create a pull request into CFIN-204 instead.

2020-09-28 15:21 UTC, closed without merging