CFIN-262 run Prettier and XO automatically
university-of-york/uoy-api-courses pull request #38
Opened 2020-09-28 15:49 UTC by ncn1

2nd try - Have initially got XO and Prettier running on push to the CFIN-262_run_Prettier_and_XO_automaticlly branch just to test it out. Prettier runs after XO, as if can change the files and these then automatically commit, which we don't want to happen if the XO check failsOnce we are happy this can move to push on dev. I notice if the XO step fails, the commit is still pushed, but marked with an X to show it has failed checks. Also need to discuss if we want to add the checks to deploy.yml, as that is also working on push, or keep it as a separate workflow.

2020-09-29 08:28 UTC, ncn1 commented on src/handler.js
> -const { transformResponse } = require("./utils/transformResponse");
XO objected to it as an unused variable

2020-09-29 15:27 UTC, RichardAllum approved these changes

2020-09-29 15:27 UTC, RichardAllum commented on src/handler.js
> -const { transformResponse } = require("./utils/transformResponse");
OK, we'll need to make sure it's there once everything has moved to dev in that case

2020-09-29 15:32 UTC, ncn1 commented on src/handler.js
> -const { transformResponse } = require("./utils/transformResponse");
Why, is XO wrong and it is being used?

2020-09-30 15:33 UTC, ce666-york requested changes
I'm requesting changes as I think the third-party action would need to be assessed before using it - however my preference would be to not use it, and either use the pre-commit hook or not run Prettier automatically (except locally in IntelliJ) at all. As I said happy to start a discussion about this!

I'm not sure why `xo` failing still causes the next step to run, as what I've read says this shouldn't be the case - it's most likely something related to the exit value from the command, so that would be the next place to investigate (although my above preference would remove the next step and so make it a non-issue).

I think the separate workflow file makes sense, as we'll want to run linting but not deployment on a pull request.

2020-09-30 15:33 UTC, ce666-york commented on .github/workflows/checks.yml
> +        run: npm run format
I'd suggest running Prettier first; no matter how unlikely it's always possible for a code change to cause test or linting errors, so I wouldn't want to create situations where the next person who comes to it has to fix errors.

2020-09-30 15:33 UTC, ce666-york commented on .github/workflows/checks.yml
> +        uses: stefanzweifel/git-auto-commit-action@v4.1.2
We should do an assessment of any third-party action we use - my preference would be to avoid using them where possible. See [this wiki page](https://wiki.york.ac.uk/display/ittechdocs/Use+of+Third+Party+GitHub+Actions ) for details.

2020-09-30 15:33 UTC, ce666-york commented on .github/workflows/checks.yml
> +        uses: stefanzweifel/git-auto-commit-action@v4.1.2
We had a discussion about the Prettier pre-commit hook a while back and decided not to use it; but running Prettier in CICD and committing changes essentially does the same thing.

I actually don't feel that strongly about whether we should do code formatting automatically or not, but if we do then I think we might as well do it on the commit hook, which forces the error to be fixed by the developer who wrote the code (see the other comment about fixing errors). Happy for a wider team discussion on this.

2020-09-30 15:33 UTC, ce666-york commented on .xo-config.json
> +    "unicorn/no-nested-ternary": "off",
I'm not hugely in favour of nested ternaries, so if `xo` thinks we should avoid them then I'm inclined to go with that

2020-09-30 15:33 UTC, ce666-york commented on package.json
> +    "check": "xo && jest",
These are great! Personally I'd like a command that does everything that I can run as a "final check" before doing a push, how would we feel about making `check` do prettier -> xo -> jest?

```suggestion
    "format": "prettier --write .",
    "lint": "xo .",
    "check": "prettier --write && xo && jest",
```

2020-10-01 08:59 UTC, ncn1 commented on .github/workflows/checks.yml
> +        run: npm run format
> I'm not sure why `xo` failing still causes the next step to run, as what I've read says this shouldn't be the case - it's most likely something related to the exit value from the command, so that would be the next place to investigate (although my above preference would remove the next step and so make it a non-issue).

XO failing does prevent the next step running, it just doesn't cause the commit push to fail

2020-10-01 09:21 UTC, ce666-york commented on .github/workflows/checks.yml
> +        run: npm run format
Oh that's fine then - we have the "Require status checks to pass before merging" option enabled in our `dev` branch protection rules, so a pull request won't be able to be merged unless it passes all checks

2020-10-01 13:02 UTC, ncn1 commented on .github/workflows/checks.yml
> +        uses: stefanzweifel/git-auto-commit-action@v4.1.2
I'm happy to remove it. The acceptance criteria for the story, is, however, 'Linting and code formatting runs automatically' - so would need to remove the code formatting bit if we aren't going to do that.

2020-10-01 13:28 UTC, ncn1 commented on package.json
> +    "check": "xo && jest",
Your suggestion will unfortunately not run. I've done some googling to try and work out how to do this, as I also think it would be good to have in one script, but haven't found out how to do it.

2020-10-01 13:35 UTC, ce666-york commented on .github/workflows/checks.yml
> +        uses: stefanzweifel/git-auto-commit-action@v4.1.2
If code formatting runs whenever you save a file in IntelliJ, that's still automatically 😃 but feel free to update the criteria if you think it should be more general, that was always the intention of it I think

2020-10-01 13:40 UTC, FergusMcGlynn commented on .github/workflows/checks.yml
> +        uses: stefanzweifel/git-auto-commit-action@v4.1.2
Perhaps what we want to do in the CI pipeline is run a check to see if the code conforms to the `prettier` rules, and if not then terminate, just like when there's an XO error. You can [run `prettier --check`](https://prettier.io/docs/en/cli.html#--check) to test whether or not the code is correctly formatted. A failure will cause the developer to fix their formatting. I think that would be better than trying to auto-commit formatted code.

2020-10-01 14:10 UTC, ncn1 commented on .xo-config.json
> +    "unicorn/no-nested-ternary": "off",
This is the code that rule objects to:
        course.distanceLearning = distanceLearning === "yes" ? true : distanceLearning === "no" ? false : null;
This can be recoded as
        course.distanceLearning = transformedDistanceLearning(distanceLearning);
  which is calling the following function:
 const transformedDistanceLearning = (originalDistanceLearning) => {
    if (originalDistanceLearning === "yes") {
        return true;
    }
    if (originalDistanceLearning === "no") {
        return false;
    }
    return null;
};
In this case, I prefer the original, the recoded version seems unnecessarily long winded.

2020-10-01 14:30 UTC, FergusMcGlynn commented on .xo-config.json
> +    "unicorn/no-nested-ternary": "off",
I think this code (that involved the nested ternary) might have been updated now. Richard merged in CFIN-263 and I think that might have removed it. If so, merging from `dev` into your branch will update the code and maybe remove the need for this XO override?

2020-10-01 14:37 UTC, ce666-york commented on package.json
> +    "check": "xo && jest",
[This page](https://gist.github.com/coryhouse/b26f49bead69066844d9) led me to a solution that seems to work:

```suggestion
    "format": "prettier --write .",
    "lint": "xo .",
    "check": "npm run format && npm run lint && npm run test"",
```

2020-10-01 14:58 UTC, FergusMcGlynn approved these changes
Quite a few of the changed files are actually from Richard's merge into `dev` earlier (which weren't merged into `CFIN-204`, hence turning up in this PR). I'm largely ignoring those changes - although they look fine.

2020-10-01 14:58 UTC, FergusMcGlynn commented on .xo-config.json
> +    "no-warning-comments": "off",
I'm guessing this rule has been disabled to allow `// TODO` style comments. Personally, I'm not a huge fan of them, and I don't think they conform to clean code, so I'd opt to get rid of the `// TODO` comment and re-instate this rule. But it's not a big deal.

2020-10-01 15:02 UTC, FergusMcGlynn commented on .github/workflows/checks.yml
> +        run: npm run lint
I think the `name`s here could be slightly more descriptive:
```suggestion
      - name: Check code formatted correctly
        run: npm run checkformat

      - name: Check code conforms to linting rules
        run: npm run lint
```

2020-10-01 16:18 UTC, ncn1 commented on .xo-config.json
> +    "no-warning-comments": "off",
I find TODO comments useful, when used judiciously, which I think our team do. Changing it here would also mean me removing someone else's TODO comment.

2020-10-02 11:29 UTC, FergusMcGlynn commented on package.json
> +    "check": "npm run checkformat && npm run lint && npm run test",
Thanks for adding these! :)

2020-10-02 11:56 UTC, ce666-york approved these changes

2020-10-02 12:45 UTC, merged