CFIN-340 & CFIN-342 Log and ignore returned non course entries, log other errors
university-of-york/uoy-api-courses pull request #45
Opened 2020-10-15 15:03 UTC by ncn1

Did these both together because I needed to log my errors to be able to debug my logging of non-course entries.

2020-10-15 15:12 UTC, RichardAllum requested changes

2020-10-15 15:12 UTC, RichardAllum commented on src/utils/transformResponse.js
> +        const actualCourse = () => {
I would be tempted to name this `validateCourse` or similar and put it down with `transformDepartment` rather than nesting it here, the logic looks good though!

2020-10-16 09:43 UTC, FergusMcGlynn requested changes

2020-10-16 09:43 UTC, FergusMcGlynn commented on src/handler.js
> +            console.log(searchResponse.statusText);
Should these maybe use `console.error` rather than `console.log`? `console.log` is `INFO` whereas `console.error` is `ERROR`. Not a massive issue.

2020-10-16 09:43 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +        const actualCourse = () => {
If it were to be renamed `validateCourse` then I wouldn't expect it to return anything - just throw an error when given course is not valid. But I agree that it's not obvious what a function called `actualCourse` would do.

2020-10-16 09:43 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +        const actualCourse = () => {
And I agree that defining the function inside a `map` makes this outer function a little hard to understand

2020-10-16 10:10 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +        const actualCourse = () => {
How about defining a new private (i.e. non-exported) function `isValidCourse()`, something like
```
const isValidCourse = (course) => !!course.department
```
and then this function can make use it with something like
```
if (!isValidCourse(course)) {
  console.log("Invalid course etc")
  return null;
}
const transformedCourse = course;
transformDistanceLearning(transformedCourse);
transformDepartment(transformedCourse);
return transformedCourse;
```

2020-10-16 10:24 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +    }
Is `department` the only thing that makes a course valid/invalid?

2020-10-16 10:25 UTC, ncn1 commented on src/utils/transformResponse.js
> +        const actualCourse = () => {
I think I just committed my refactoring of this as you were adding this comment - obviously thinking on similar lines!

2020-10-16 10:27 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +    console.error("Invalid course entry " + course.title);
On this occasion, I think maybe `console.warn` is more appropriate than `console.error`, as the Courses API was able to fulfil the request, but it's making a note that there's something not right about one of the Funnelback courses. Again, not a big issue.

2020-10-16 10:32 UTC, FergusMcGlynn commented on src/handler.test.js
> +test("Response results do not contain entries from Funnelback that have no department", async () => {
This test looks good to me! I'm just wondering whether we need to have so much detail in each of the `results` entries, as it makes the test quite long, and really the only attribute that's being tested is `department` so could we strip out some/all of the attributes that don't take part in the test?

2020-10-16 10:40 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +    }
I guess I'm struggling to understand why we deem a course without a department as invalid, and other courses with missing metadata valid. What is it about department that makes a course not valid?

2020-10-16 10:49 UTC, ncn1 commented on src/utils/transformResponse.js
> +    }
It's the only thing that will cause this app to error if it's missing. When we add the '&smeta_contentType=course' to the URL we are using for Funnelback, that should do the real work of preventing non-courses appearing in these results. (I'll do that once this change is merged - it's been useful for getting the error messages in dev to have a search that will return invalid entires).

2020-10-16 10:49 UTC, ncn1 commented on src/utils/transformResponse.js
> +    }
Thinking about this further, if an actual course entry is on the website but with some of the metadata missing, I think we'd want that to show up so it would be immediately obvious something was wrong to people using the search and would hopefully get reported and corrected. Just not showing them would hide the problem, and it's too easy for error alerts to be ignored by IT staff who don't necessarily understand their significance.

2020-10-16 10:57 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +    }
Why does this app error if the `department` is missing?

2020-10-16 11:04 UTC, ncn1 commented on src/utils/transformResponse.js
> +    }
It's the transformDepartment function that errors. So I suppose the question is should we test for more missing data in isValid, or should we just prevent the transformDepartment function from erroring if no department is specified?

2020-10-16 11:06 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +    }
In that case, I think we should change `transformDepartment` so that it can handle a course without a department, and that's all. I don't think we need to remove any courses from the results - because as far as I can tell they're all valid (at this stage) no matter what metadata is present/missing.

2020-10-16 13:11 UTC, ncn1 commented on src/handler.test.js
> +test("Response results do not contain entries from Funnelback that have no department", async () => {
The Funnelback search will return all the attributes, but they may be null. Therefore to make the test as near to what will really happen, it's best to have all the attributes.

2020-10-16 13:30 UTC, FergusMcGlynn commented on src/handler.test.js
> +test("Response results do not contain entries from Funnelback that have no department", async () => {
Fair enough. I thought maybe it'd be good to focus on testing just the new functionality rather than also testing pre-existing functionality like department and distance learning transformation. I take your point though.

Having said that, maybe we don't want to suppress courses from the results, even if they have a null department, so perhaps this test isn't needed?

2020-10-16 13:58 UTC, ncn1 commented on src/handler.test.js
> +test("Response results do not contain entries from Funnelback that have no department", async () => {
But we want to be sure it handles courses with missing metadata, so I've changed the title.

2020-10-16 14:07 UTC, FergusMcGlynn commented on src/handler.js
> +        const results = transformedResults.filter(Boolean); // Removes null values
Clean code would probably say to have a descriptively named function rather than a comment explaining what's going on, e.g.
```
const removeNullValues = (array) => array.filter(Boolean);
...
const results = removeNullValues(transformedResults);
```

2020-10-16 14:11 UTC, FergusMcGlynn commented on src/handler.test.js
> +test("Response results from Funnelback with missing metadata are returned OK", async () => {
I'm not sure this test needs 3 results when 2 of them aren't verifying the new functionality. There's already a test above for the existing functionality and those 2 results are re-testing it here.

2020-10-16 14:17 UTC, ncn1 commented on src/handler.js
> +        const results = transformedResults.filter(Boolean); // Removes null values
Thanks - still struggling with doing this sort of thing in Javascript, and I've added this to my Javascript crib sheet. But actually no longer any need to remove nulls at all, as no null result entries being returned now. So will revert to previous code.

2020-10-16 14:25 UTC, FergusMcGlynn commented on src/utils/transformResponse.test.js
> +        const positiveInput = [{ department: "Department", distanceLearning: "Yes" }];
I'm guessing we don't need `department` in here now that courses without departments are being left in the results?

2020-10-16 14:26 UTC, ncn1 commented on src/handler.test.js
> +test("Response results from Funnelback with missing metadata are returned OK", async () => {
May not be testing new functionality, but is testing functionality that has not been tested already. It is testing that multiple results get returned as expected, as well as that a course with missing metadata gets returned. In fact I should probably have picked up in the code review prior to my changes that only single results were being tested, and asked for a test for more than one entry in the results array.

2020-10-16 14:27 UTC, ncn1 commented on src/utils/transformResponse.test.js
> +        const positiveInput = [{ department: "Department", distanceLearning: "Yes" }];
Good spot!

2020-10-16 14:29 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +        console.warn("Department missing for " + course.title);
I'm not sure this `console.warn` is necessary anymore. I doubt we'll be looking through the logs to see if any Funnelback records have missing metadata, and as we've discussed, is `department` any more or less important than any other metadata? It seems a bit odd to me to log missing department specifically.

2020-10-16 14:33 UTC, ncn1 commented on src/utils/transformResponse.js
> +        console.warn("Department missing for " + course.title);
It's a sort of 'why not?' We are testing for it, no big deal to log it, just might be helpful for debugging at some point. Or does it cost us?

2020-10-16 14:36 UTC, ncn1 commented on src/utils/transformResponse.js
> +        console.warn("Department missing for " + course.title);
Also, could be a handy check that we are successfully ensuring only courses are returned - we actually shouldn't get any logs like this.

2020-10-16 14:52 UTC, FergusMcGlynn commented on src/utils/transformResponse.js
> +        console.warn("Department missing for " + course.title);
I doubt there are any practical cost issues with logging.

I'm just not convinced, at this stage, that we know which bits of metadata being null are problematic, so I don't think we should be logging warnings until we do know for sure. Also, if we're going to log about missing department, shouldn't we log about missing title, award, start year etc? It doesn't feel consistent. 

I know this is only one item of logging and it probably won't get triggered often, but I think it's good to only log when you know you definitely want the information. Over time, it's easy to fill the logs up with information that's not particularly important which makes it harder to find the things that you really do want.

If you really do want to log this - I'd advocate making it `console.info` rather than `console.warn`. I misunderstood what the goal was when we first discussed what logging level it should have.

2020-10-16 14:56 UTC, FergusMcGlynn commented on src/handler.test.js
> +test("Response results from Funnelback with missing metadata are returned OK", async () => {
In that case, it might be good to split it into two tests, and be explicit that two different things are being tested?

2020-10-16 15:20 UTC, FergusMcGlynn approved these changes

2020-10-19 08:31 UTC, RichardAllum commented on src/handler.test.js
> +    expect(result.body).toEqual(JSON.stringify(expectedResult));
I'm a bit confused, is this test showing the API returning a non-course entry now instead of skipping it?

Is this to show confidence that funnelback will only return courses now?

2020-10-19 08:39 UTC, ncn1 commented on src/handler.test.js
> +    expect(result.body).toEqual(JSON.stringify(expectedResult));
This **is** this test showing the API returning a 'non-course' entry (ie. missing course metadata) now instead of skipping it.
It's to show that this API handles it without erroring. I haven't done the change to the URL being used for Funnelback to try and  ensure it only brings back courses yet - but that will not prevent an actual course not having department metadata, for instance, so this app needs to handle it.

2020-10-19 08:44 UTC, ncn1 commented on src/handler.test.js
> +    expect(result.body).toEqual(JSON.stringify(expectedResult));
That's assuming you meant the test above the comment!

2020-10-19 09:01 UTC, RichardAllum approved these changes

2020-10-19 09:01 UTC, RichardAllum commented on src/handler.test.js
> +    expect(result.body).toEqual(JSON.stringify(expectedResult));
I did, and OK - I think this all works then!

2020-10-19 09:01 UTC, RichardAllum approved these changes

2020-10-19 09:28 UTC, ChristianBeddows approved these changes

2020-10-19 09:46 UTC, merged