CFIN-288 Remove request validation from URLConstructor
university-of-york/uoy-api-courses pull request #51
Opened 2020-10-20 14:06 UTC by RichardAllum

This is the simplest example approach to removing the validation code from the utility function that constructs URLs.

I think there's a lot to talk about here relating to how we want to develop the API and which (if any) code quality standards we want to uphold. We currently don't have any form of type validation, for example. I'll put more in depth comments on the code itself.

2020-10-20 14:08 UTC, RichardAllum commented on src/handler.js
> -const ClientError = require("./errors/ClientError");
In this implementation we're not using ClientError at all. I personally prefer this as I'm against using Exceptions to control the flow of an application, but there are also benefits to using them when you have a complex system.

2020-10-20 14:10 UTC, RichardAllum commented on src/utils/constructFunnelbackUrls.js
> -    if (!parameters || !parameters.search) {
The changes to make this function pure also make it so that it can return an invalid URL (when using https://york.ac.uk/search instead of york.funnelback). Is this something we want to do or avoid?

2020-10-20 14:16 UTC, RichardAllum commented on src/handler.js
> +        if (!event.queryStringParameters || !event.queryStringParameters.search) {
Here we're doing the request validation in the main body of the lambda. I've been thinking of this as analogous to a controller method where it would probably be OK to validate the request, but it would be better to have a custom validation method.

2020-10-20 14:17 UTC, RichardAllum commented on src/handler.js
>              default:
Now we're only catching default exceptions in order to return a sensible response to the user and log them, so we won't need the switch statement.

2020-10-20 14:18 UTC, RichardAllum commented on src/handler.js
>  module.exports.courses = async (event) => {
I think we're having to declare everything so awkwardly because we're not using Babel or any kind of preprocessor, would it be better if we installed babel so our code can more closely align with other repos?

2020-10-20 14:25 UTC, RichardAllum commented
The cleanest solution for validation of the request and then returning the response etc. would be to create Request and Response objects/Data Types that are passed through to methods. This is how express and a lot of other simple API/servers work.

In order to do this it would be good to be able to declare types and also have a better system for importing/working with modules, which we don't yet have.

2020-10-20 14:53 UTC, ncn1 commented on src/utils/constructFunnelbackUrls.js
> -    if (!parameters || !parameters.search) {
I think I would have a function in utils that accepts the parameters, checks that the search parameter is present, and that max and offset are valid numbers, and would make this throw an error if not. I would call this at the start of constructFunnelbackUrls.js, instead of doing it in the handler. Then if this hasn't thrown an error, there is no need to test for the presence of parameters.search in constructFunnelbackUrls.js as that check has already been called by constructFunnelbackUrls.js itself. It also makes more sense to call the parameter validation from here as they are really parameters to the URL construction process.

2020-10-20 14:54 UTC, ncn1 commented on src/handler.js
> +        if (!event.queryStringParameters || !event.queryStringParameters.search) {
See my reply to your previous comment - I'd remove this check from here.

2020-10-20 16:51 UTC, ce666-york requested changes
I've marked as request changes as I think we should tidy up the code surrounding `ClientError` (Ferg's suggestions), but other than that I'm happy with this version of the code :+1:

2020-10-20 16:59 UTC, ce666-york commented on src/utils/constructFunnelbackUrls.js
> -    if (!parameters || !parameters.search) {
Having seen Ferg's PR description [here](https://github.com/university-of-york/uoy-api-courses/pull/50), it seems that API request validation could also handle the former.

2020-10-21 09:54 UTC, FergusMcGlynn commented on src/utils/constructFunnelbackUrls.js
> -    if (!parameters || !parameters.search) {
If we turn on query parameter validation in the API then yes, no requests should make it in to `handler.js` without a `search` parameter. Personally, I'd probably still be defensive - but there shouldn't be any need to be with param validation.

2020-10-21 11:03 UTC, RichardAllum commented on src/handler.js
>  module.exports.courses = async (event) => {
I think it's a combination of those two issues and a lack of type validation, which leads to issues with writing type-safe code. PropTypes would potentially work as a solution for the typing issue but is intended for use with React Components, so it would be a bit of a kludge to use it here.

2020-10-21 11:40 UTC, RichardAllum commented on src/utils/constructFunnelbackUrls.js
> -    if (!parameters || !parameters.search) {
Sounds good, I've left the validation in the handler for now. I didn't change the signature of  `coursesUrl` as we don't have any typechecking yet and we will need to add in extra parameters for filters, ideally we would declare a parameter object that has set properties that the UrlConstructor would take in I think.

2020-10-21 13:26 UTC, FergusMcGlynn commented on src/handler.js
>  module.exports.courses = async (event) => {
[Other people](https://blog.jim-nielsen.com/2020/proptypes-outside-of-react-in-template-literal-components/) use `PropTypes` outside of React - so we wouldn't be alone. But it looks a little messy because you have to write code to run the `PropTypes` check, as well as defining the `PropTypes` rules. React runs the checks for you so there you just have to write the rules.

It seems to me that TypeScript would solve both of the issues that you've raised here - type checking and Babel integration. I know that Special Circumstances tend to use TypeScript for most things. Might be worth considering. I'd be open to it.

2020-10-22 08:59 UTC, ChristianBeddows commented on src/handler.js
>  module.exports.courses = async (event) => {
I'm also open to trying Typescript!

2020-10-22 09:56 UTC, ce666-york approved these changes

2020-10-26 07:44 UTC, merged