CFIN-416 Reduce build package size by excluding unneeded items
university-of-york/uoy-api-courses pull request #56
Opened 2020-11-12 10:40 UTC by ChristianBeddows

These files aren't needed in the build package deployed by serverless. Removing them reduces the package size from about 215 kB to about 65 kB.

2020-11-12 11:41 UTC, ncn1 approved these changes

2020-11-12 13:09 UTC, ce666-york approved these changes

2020-11-12 13:14 UTC, FergusMcGlynn requested changes

2020-11-12 13:14 UTC, FergusMcGlynn commented on serverless.yml
> +    - README.md
Given the number of individual excludes we have here, would it be tidier perhaps to[ only *include* the files/folders we do want bundled](https://www.serverless.com/framework/docs/providers/aws/guide/packaging/)? Which might just be `node_modules` and `src`? e.g.
```
package:
  exclude:
    - ./**
  include:
    - src/**
    - node_modules/**
```
I'm not sure if this would work - but it might be worth trying?

2020-11-12 17:30 UTC, ce666-york commented on serverless.yml
> +    - README.md
I considered this for Course Search but ultimately decided against it because I felt that when adding a new file, it would be better to have a package size increase flagged up for a file that we don't want to include in the bundle, rather than have a file that we do want to include in the bundle excluded without warning.

There may be other ways around it though, or people may disagree - happy to discuss 🙂

2020-11-13 09:57 UTC, FergusMcGlynn commented on serverless.yml
> +    - README.md
Fair points! I think it's more likely that we'd create files that don't need to be included in the bundle, and then for consistency we ought to explicitly exclude them in `serverless.yml` and this becoming an even longer list of exceptions, and easy to forget to keep up-to-date. I guess it comes down to whether we think that new files (outside of `/src`) are more likely or less likely to be needed in the bundle. My suspicion is they're less likely to be needed in the bundle. Happy to be persuaded otherwise!

2020-11-16 15:06 UTC, FergusMcGlynn approved these changes

2020-11-16 15:07 UTC, merged