CFIN-252 Log requests to the API
university-of-york/uoy-api-courses pull request #68
Opened 2021-05-24 14:14 UTC by ncn1

This creates a log of each request using these AWS [audit log policy guidelines](https://wiki.york.ac.uk/pages/viewpage.action?spaceKey=CLOUD&title=0008+-+Audit+Log+Policy).

2021-05-24 14:21 UTC, ncn1 commented on src/utils/auditLogEntry.test.js
> +test("Required data added to audit log when supplied in event object", () => {
This closely replicates the event object being returned by API gateway, to demonstrate it works with realistic data.

2021-05-24 14:25 UTC, ncn1 commented on src/utils/auditLogEntry.js
> +            client: event?.requestContext?.identity?.sourceIp || null,
Null is being explicitly added here, as JSON.stringify will ignore any entries that have an undefined variable ie. they are missed out entirely in the returned string. The audit log policy guidelines specify 'required' against several entries, these are the ones where null is being explicitly returned if undefined.

2021-05-25 11:55 UTC, FergusMcGlynn commented on src/handler.js
> +        console.log(auditLogEntry(event, 200, numberOfMatches));
Two minor things:

1. Even though they're functionally equivalent, it might be nicer to use `console.info` rather than `console.log`. `console.info` indicates to other developers that this logging is at `info` level, as distinct from `warn` level or `error` level, whereas `console.log` doesn't give any indication of the alert level of what's being logged
2. Rather than hard coding the literal `200` for the status, maybe consider using `searchResponse.status` instead? I'd find that slightly easier to understand.

2021-05-25 12:02 UTC, FergusMcGlynn commented on src/utils/auditLogEntry.js
> +        schemaURI: "https://github.com/university-of-york/uoy-api-courses/README.md",
I'm a bit confused by what `schemaURI` is. The documentation does give an example where it is set to a repo's README file, but that doesn't align with the purpose of the field (`A link to the schema, detailing the fields used in the request/response`). Maybe it should be [the API specification](https://university-of-york.github.io/uoy-api-courses/) instead? Worth clarifying with someone from the Cloud Architecture Board, or Dan Miller perhaps?

2021-05-25 12:18 UTC, FergusMcGlynn commented on src/utils/auditLogEntry.test.js
> +    );
Might be slightly easier to read/understand as a javascript object rather than as JSON? `JSON.parse()` just turns this into a javascript object anyway.

```suggestion
    const event = {
        "resource": "/courses",
        "path": "/courses",
        "httpMethod": "GET",
        "headers": {
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
            "Accept-Encoding": "gzip, deflate, br",
            "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
            "CloudFront-Forwarded-Proto": "https",
            "CloudFront-Is-Desktop-Viewer": "true",
            "CloudFront-Is-Mobile-Viewer": "false",
            "CloudFront-Is-SmartTV-Viewer": "false",
            "CloudFront-Is-Tablet-Viewer": "false",
            "CloudFront-Viewer-Country": "GB",
            "Host": "k0fqbcuftg.execute-api.eu-west-1.amazonaws.com",
            "sec-ch-ua-mobile": "?0",
            "sec-fetch-dest": "document",
            "sec-fetch-mode": "navigate",
            "sec-fetch-site": "none",
            "sec-fetch-user": "?1",
            "upgrade-insecure-requests": "1",
            "User-Agent":
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
            "Via": "2.0 bf4a364e1dd23fe6634f1bf013457c5c.cloudfront.net (CloudFront)",
            "X-Amz-Cf-Id": "7Px4kURZfIuh4B09Wv6vM5cSpbVXaOv1pW6h0eBMnHPpsJVQ19QtuA==",
            "X-Amzn-Trace-Id": "Root=1-60a6734a-06f7e1dd276e8dc64be2d129",
            "X-Forwarded-For": "144.32.90.155, 130.176.97.157",
            "X-Forwarded-Port": "443",
            "X-Forwarded-Proto": "https"
        },
        "queryStringParameters": {
            "search": "biology"
        },
        "requestContext": {
            "identity": {
                "sourceIp": "144.32.90.155"
            },
            "apiId": "theApiId"
        }
    }
```

2021-05-25 13:17 UTC, ncn1 commented on src/utils/auditLogEntry.js
> +        schemaURI: "https://github.com/university-of-york/uoy-api-courses/README.md",
I think the API specification makes more sense, as you say. When I coded that, I was still at the 'let's get something working' stage and so wasn't particularly thinking about the most appropriate hard-coded string. Then I didn't revisit it.

2021-05-25 13:29 UTC, ncn1 commented on src/utils/auditLogEntry.test.js
> +    );
Yes - initially it was a simple way of replicating exactly what I was getting out of the API, which was being logged as a piece of JSON that I just pasted in. I was also worried that linting would mess it all up, but it has just removed the double-quotes from the keys where they aren't needed.

2021-05-25 13:40 UTC, FergusMcGlynn approved these changes

2021-05-25 14:53 UTC, ChristianBeddows approved these changes

2021-05-26 09:30 UTC, RichardAllum approved these changes

2021-05-26 12:57 UTC, ce666-york requested changes

2021-05-26 12:57 UTC, ce666-york commented on src/utils/auditLogEntry.js
> +module.exports.auditLogEntry = (event, statuscode, numberOfMatches) => {
This looks good! In case it's of interest and as a potential point of reference, here's [a snippet](https://gist.github.com/IPWright83/da7679885283051a7d753ba792da82d2) from Ian that does a similar thing (not yet in prod)

2021-06-03 08:36 UTC, ncn1 commented
> * Do we need the `logType` parameter? If we call this function using `console.info` or `console.error`, does that capture this information and therefore make `logType` redundant? Perhaps not - I'm just flagging it up as a possible source of duplication

It's needed for the type attribute on the log row, a required attribute in the  [audit log policy guidelines](https://wiki.york.ac.uk/pages/viewpage.action?spaceKey=CLOUD&title=0008+-+Audit+Log+Policy)

2021-06-03 08:55 UTC, ncn1 commented
> I think it'd be nice to use a `BAD_REQUEST` constant rather than having `400` peppered around the code. Perhaps we could use [this library](https://github.com/prettymuchbryce/http-status-codes)? Or maybe there are better options?
I think this would be a good idea, but that library is ES6 and this project isn't, I fear having another couple of days getting tangled up with import problems again. Perhaps leave for now and have a technical debt task to upgrade this to ES6, or at least be compatible with it (this has been done for the tests but not the main code)?

2021-06-03 09:03 UTC, FergusMcGlynn commented
> > I think it'd be nice to use a `BAD_REQUEST` constant rather than having `400` peppered around the code. Perhaps we could use [this library](https://github.com/prettymuchbryce/http-status-codes)? Or maybe there are better options?
> > I think this would be a good idea, but that library is ES6 and this project isn't, I fear having another couple of days getting tangled up with import problems again. Perhaps leave for now and have a technical debt task/subtask to upgrade this to ES6, or at least be compatible with it (this has been done for the tests but not the main code)?

Hmm - in that case, how about defining the relevant constants in `constants.js` for now - maybe it'd just be `{ BAD_REQUEST: 400 }` (unless there are others, e.g. 200)? I fear that a tech debt task to upgrade to ES6 *and* tidy up the code with constants might never get done...

2021-06-07 15:34 UTC, ce666-york approved these changes

2021-06-07 15:34 UTC, ce666-york commented on src/handler.js
> +            console.error(logEntry(event, HTTP_CODES.BAD_REQUEST, LOG_TYPES.ERROR, errorDetails));
Just had a thought, we might not want to receive a whole host of alerts for every user error once we get alerting set up, so we could log these as warnings and have the option of handling them differently:

```suggestion
            console.warn(logEntry(event, HTTP_CODES.BAD_REQUEST, LOG_TYPES.ERROR, errorDetails));
```


(for example, another way you can trigger alerts in AWS is if a number of messages matching a filter you configure passes a certain threshold e.g. 10 in a minute - so we could for example choose to trigger an email/Slack message if there are a large number of warnings, which could signify a larger problem).

2021-06-08 08:50 UTC, merged