Bump xo & serverless, adopt ES6 syntax
university-of-york/uoy-api-courses pull request #86
Opened 2022-03-17 15:24 UTC by ChristianBeddows

This PR resolves 8 **high** & 7 **moderate** vulnerabilities. 11 **moderate** vulnerabilites remain, but we would need to upgrade to serverless 3 to resolve these. 

Bumping xo brought in an updated ruleset, which preferred use of ES6 syntax. As I couldn't think of any good reason not to and as I feel it's preferential, I have updated our code to adhere to ES6 syntax.

I've also resolved the serverless deprecation warnings, which should make it a bit easier to upgrade to serverless 3 in the future. 

I've deployed the API to my sandbox and it appears to work perfectly, 207 results for "maths"

(Due to Github outages I've had to re-write this description more than once, so I apologise if I've missed out any details in this version)

2022-03-17 15:36 UTC, ChristianBeddows commented on package.json
> +  "type": "module",
This means "Treat all our javascript as modular javascript, rather than commonjs global scripts"

2022-03-17 15:36 UTC, ChristianBeddows commented on serverless.yml
> -    - package.json
I can understand why this file was initially excluded - because we won't need the dependency registry in the deployed code.

However, `package.json` is what usually identifies a node project/module - I think if we don't include it, we might not get the right access to built-in node modules like `path`, `url`, `child_process` or `buffer`.

More importantly (in this case), `package.json` usually contains descriptive information about a node module/project - in this case we want `"type": "module"` so that our js is treated as modular. Other important descriptive properties include: `main`, `bin`, `dist` and `types`

2022-03-17 16:46 UTC, FergusMcGlynn commented on package.json
> +    "deploy": "serverless deploy",
I believe `--env` has been doing it's job. That deprecation warning comes from Serverless, but the `--env` is there for the [serverless-dotenv-plugin](https://www.serverless.com/plugins/serverless-dotenv-plugin). When running `npm run deploy:dev`, it looks like this:
```
$ npm run deploy:dev                                                        
                                                                            
> uoy-api-courses@1.0.0 deploy:dev                                          
> serverless deploy --env development                                       
                                                                            
Serverless: DOTENV: Loading environment variables from .env.development:    
Serverless:      - BASE_URL                                                 
Serverless:      - COLLECTION                                               
Serverless:      - FORM                                                     
Serverless:      - PROFILE                                                  
Serverless:      - SMETA_CONTENT_TYPE                                       
Serverless: Deprecation warning: Detected unrecognized CLI options: "--env".
```

Note the output around `Loading environment variables from .env.development`. In contrast, when running `npm run deploy`:
```
$ npm run deploy

> uoy-api-courses@1.0.0 deploy
> serverless deploy --env production

Serverless: DOTENV: Loading environment variables from .env.production:
Serverless:      - BASE_URL
Serverless:      - COLLECTION
Serverless:      - FORM
Serverless:      - PROFILE
Serverless:      - SMETA_CONTENT_TYPE
Serverless: Deprecation warning: Detected unrecognized CLI options: "--env".
```

So I'm not sure about removing the `--env` configuration just yet. I think when we upgrade to Serverless v3 then we will need to work out whether the Serverless Dotenv Plugin is still the right to get our environment variables into the Lambda's environment - it might well be, or there might be a better way.

If you definitely want to remove the `--env` configuration then I think it'd be good to add some content to the `README` explaining to future developers how to easily switch between environments when deploying. The current solution makes it really easy to deploy the staging version of the app to your sandbox, and then deploy the production version of the app to your sandbox. While it's not that much effort to change a line in a file, it might not be that easy to remember.

2022-03-17 16:48 UTC, rmil reviewed
Just some areas that could potentially have some polish, but looks pretty good! Very much a fan of the ES6 stuff!

2022-03-17 16:48 UTC, rmil commented on package.json
> +    "deploy": "serverless deploy",
Looking in `serverless.yml` it appears that is only setting the tag on the stack? I think the envrionment swapping is handled by `serverless-dotenv-plugin` which checks `NODE_ENV` to choose which env file to use. So should we re-add `deploy:dev` just setting `NODE_ENV`? Although I'm not too familiar with what magic is happening with serverless behind the scenes

2022-03-17 16:48 UTC, rmil commented on .xo-config.json
> +    "import/extensions": "off",
How come this was needed to be added?

2022-03-17 16:48 UTC, rmil commented on src/utils/constructFunnelbackUrls.test.js
> +import { coursesUrl } from "./constructFunnelbackUrls.js";
Could this `.js` extension be removed?

2022-03-17 16:48 UTC, rmil commented on src/utils/format.js
> +import { HTTP_CODES } from "../constants/constants.js";
Could this `.js` extension be removed?

2022-03-17 16:48 UTC, rmil commented on src/utils/logEntry.test.js
> +import { logEntry } from "./logEntry.js";
Here also, I don't think they're necessary since it should be able to figure it out

2022-03-17 16:54 UTC, FergusMcGlynn commented on package.json
> +    "deploy": "serverless deploy",
Also, I don't think `DEPLOY_ENVIRONMENT` controls which `.env` file gets loaded - I think it just defines the `status` tag value of the deployed AWS resources. So it's not really doing an equivalent job.

2022-03-17 16:57 UTC, FergusMcGlynn commented on .github/workflows/deploy.yml
> +        run: npm run deploy
I'm fairly sure that this change will result in the production version of the app being deployed to the staging environment (i.e. the staging environment will query the production Funnelback collection, rather than the staging Funnelback collection (`default_preview`). I've elaborated on this in other comments.

2022-03-17 16:58 UTC, FergusMcGlynn requested changes
There are some excellent changes here. I just want us to think twice before removing the `--env` configuration because I believe it's still needed.

2022-03-18 09:32 UTC, ChristianBeddows commented on src/utils/constructFunnelbackUrls.test.js
> +import { coursesUrl } from "./constructFunnelbackUrls.js";
So, there's a fundamental difference here that we need to take into account. We've switched from using commonjs `require` to using ES Module `import`, which were developed by different organisations (mozilla vs ECMA), and both methods have slightly different specifications. 

In a nutshell, commonjs `require` statements can guess at file extensions and make some default presumptions about what to expect. Node ES module resolution _**will not**_ attempt to guess or default to file extensions - this is what causes the `MODULE_NOT_FOUND` error we've seen whilst working on this ticket.

When we run the tests, babel transpiles our ES6 code into commonjs that jest can understand - which means it can guess the extensions, and specifying `.js` is unnecessary - which is why the tests pass without the extension.

However, our lambda environment will run the source javascript as is - we do not compile or bundle our code for the lambda - and will treat our files as ES modules, thus making the explicit `.js` extensions necessary.

As this means we need to include these extensions but there's no clear indicator locally, I've updated `xo-config` to include `"node/file-extension-in-import": ["error", "always"]` which enforces the use of extensions throughout the project.

It is possible to instruct node to guess at file extensions using the CLI flag `--experimental-specifier-resolution=node` but this would require some messy changes to our npm scripts, and I've decided not to do so.

If this was a Typescript project, it would be very easy to configure this behaviour in `tsconfig.json`

2022-03-18 09:33 UTC, ChristianBeddows commented on src/utils/format.js
> +import { HTTP_CODES } from "../constants/constants.js";
See https://github.com/university-of-york/uoy-api-courses/pull/86#discussion_r829831118

2022-03-18 09:33 UTC, ChristianBeddows commented on src/utils/logEntry.test.js
> +import { logEntry } from "./logEntry.js";
See https://github.com/university-of-york/uoy-api-courses/pull/86#discussion_r829831118

2022-03-18 09:41 UTC, ChristianBeddows commented on src/integrationTests/logger.integration.test.js
>      const testAppFilePath = path.join(__dirname, "./demoLogger.js");
I don't know how that's passing - the reason for the eslint suppression is that `__dirname` is forbidden by eslint specifications - without the suppression you get the following error:
![Screenshot from 2022-03-18 09-38-51](https://user-images.githubusercontent.com/17494696/158978818-ca3a1740-3761-4a8d-8779-c99a4a76720e.png)

You're right that we can remove the `.js` extension and xo won't complain, as it doesn't recognise this as an import. However I'd like to match the convention for our imports if we can!

Do you not get the xo error locally?

2022-03-18 09:42 UTC, ChristianBeddows commented on .xo-config.json
> +    "import/extensions": "off",
I did initially add it to suppress some xo errors but I think this was before I fully figured out all the extensions caveats.
I reviewed the specification for this linting rule and I think we do want it, so I've now explicitly enforced it.

2022-03-18 09:44 UTC, ChristianBeddows commented on package.json
> +    "deploy": "serverless deploy",
Yeah you're right, I did get this wrong - I thought I'd run `npm run deploy` locally as it was defined and seen it loading from `.env.development` but I suspect that I might have checked it after modifying the scripts.

I've reverted the change to restore the previous behaviour of the deploy scripts

2022-03-18 09:45 UTC, ChristianBeddows commented on src/integrationTests/logger.integration.test.js
>      const testAppFilePath = path.join(__dirname, "./demoLogger.js");
The right thing to do would be to replace `__dirname` with a recommended solution but the solutions tended to be a fair few extra lines of code, and I didn't feel it necessary to do this for a test that is now working consistently

2022-03-18 09:46 UTC, ChristianBeddows commented on .github/workflows/deploy.yml
> +        run: npm run deploy
You're correct, great reviewing! :)

2022-03-18 09:52 UTC, FergusMcGlynn commented on src/utils/constructFunnelbackUrls.test.js
> +import { coursesUrl } from "./constructFunnelbackUrls.js";
Thanks so much for the detailed explanation - that's really helpful!

2022-03-18 09:57 UTC, FergusMcGlynn commented on package.json
> +    "eslint-config-xo": "^0.40.0",
Why do we need to include `eslint` explicitly? I thought it would be included by `xo`.

2022-03-18 09:59 UTC, FergusMcGlynn commented on package.json
> +    "deploy": "serverless deploy",
Thanks for taking another look at this :)

2022-03-18 10:29 UTC, ChristianBeddows commented on package.json
> +    "eslint-config-xo": "^0.40.0",
Yeah this is a weird one. `eslint` is indeed a dependency of `xo` so I would have expected it to be installed (and this worked locally) but when I created this PR the checks failed with the message: `Error: Failed to load plugin 'unicorn' declared in 'BaseConfig » /home/runner/work/uoy-api-courses/uoy-api-courses/node_modules/xo/config/plugins.cjs': Cannot find module 'eslint/package.json'` which implies that the `eslint` module hasn't been installed as part of the workflow's `npm ci`. 

My thinking was that npm might be treating `eslint` as a peer dependency (which isn't something I'm all that familiar with) and that explicitly depending on `eslint` might resolve this - and after doing so the workflow check passed. 

It should be unnecessary though, so for sanity's sake I'll try removing it now and seeing what happens with the workflow check

2022-03-18 10:37 UTC, ChristianBeddows commented on package.json
> +    "eslint-config-xo": "^0.40.0",
Yes that error is still happening in our checks so I think the explicit dependency is necessary

2022-03-18 10:38 UTC, rmil commented on src/integrationTests/logger.integration.test.js
>      const testAppFilePath = path.join(__dirname, "./demoLogger.js");
Gotcha, when I was testing locally, I only tested the file directly and didn't run `npm run fc` since I didn't see any highlighted errors in my IDE smh! But yeah keeping the `eslint` disable seems like it would be a good option

2022-03-18 10:41 UTC, rmil commented on src/utils/constructFunnelbackUrls.test.js
> +import { coursesUrl } from "./constructFunnelbackUrls.js";
Ah interesting! Thank for for clarifying, does make a lot more sense!  But yeah, hopefully the later added TypeScript support will help

2022-03-18 10:48 UTC, ncn1 approved these changes
Thanks for doing this - I find it much more understandable now, as I learnt with the ES6 version of javascript.

2022-03-18 12:05 UTC, FergusMcGlynn commented on package.json
> +    "eslint-config-xo": "^0.40.0",
Two things on this subject:

1. Perhaps we don't need to install all of `eslint`, perhaps we only need [eslint-plugin-unicorn](https://www.npmjs.com/package/eslint-plugin-unicorn), since that's specifically what the error refers to? I don't know if that's the case - I was planning to try it out locally but...
2. I get errors when I run `lint` locally - I've checked out the this branch, run `npm install`, run `lint` and the result looks like this:
```
> uoy-api-courses@1.0.0 lint
> xo .

node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'C:\dev\uoy-api-courses\node_modules\xo\node_modules\eslint\' imported from C:\dev\uoy-api-courses\node_modules\xo\index.js
Did you mean to import eslint/lib/api.js?
    at new NodeError (node:internal/errors:371:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:335:9)
    at packageResolve (node:internal/modules/esm/resolve:877:14)
    at moduleResolve (node:internal/modules/esm/resolve:929:18)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Process finished with exit code 1
```
It could be that this problem doesn't occur on Linux, and that's why others haven't seen it. I'll try to work out what's causing the problem. I wouldn't want us to merge this code until it works for everyone.

2022-03-18 14:48 UTC, rmil approved these changes

2022-03-18 16:32 UTC, FergusMcGlynn approved these changes

2022-03-24 15:56 UTC, merged